// Code generated by gen.go. DO NOT EDIT.

//go:build !ebitenexternaldll
// +build !ebitenexternaldll

package glfw

const glfwDLLHash = "6526954c9adfb11f933f2cacd774166917259c65f14b0b87b1d82c58976e5c83"
