// Code generated by gen.go. DO NOT EDIT.

//go:build !ebitenexternaldll
// +build !ebitenexternaldll

package glfw

const glfwDLLHash = "b4ed8dbddd26185b6f5385141b0467da2820a4beb09a614d81f75e7b86bf5978"
